### ISSUE TITLE
Confirm single app key works for other orgs

### ISSUE THREAD

**Issue by ericlifka** [purecloudlabs/skype-for-business-purecloud-app#1]
For the app to validate itself to Microsoft apis an application entry needs to be registered in the customer's Azure domain to generate an Application ID for that App-Org relationship. That App ID needs to be provided to the skype-for-business-purecloud-app via some sort of apps configuration. 

Tasks:
  - Create instruction set for configuring an app registration in a customer's azure AD
  - Expose a configuration field in apps that allows exposing data to the app
  - Use configured field from apps as source for app key on startup

**Comment by ericlifka** [comment]
Via a different way of registering a Microsoft App that @omarestrella found we think we no longer need to configure an app key per org. This would allow a fixed app key for the whole app, but this needs to be confirmed to work.

 - Make a new microsoft org with a dummy user
 - Add the purecloud skype app to the org (??? - not entirely clear on these steps)
 - Authenticate a user from that org with the purecloud skype app to confirm permissions can be granted to the app.

Documentation of these steps will need to be created for our customers, so keep track of the high level steps an org will need to follow so these can be passed off to the docs team.

**Comment by omarestrella** [comment]
In order to allow us to access the Skype APIs for a given Skype for Business organization, the application needs to be given approved by an Administrator. This can be done inside of the Azure Active Directory admin > Enterprise applications:

![image](https://user-images.githubusercontent.com/228341/33503489-e6f68dd2-d6b1-11e7-8ba8-6761467906de.png)

In order for them to be able to add us as an application, we need to be published on their "gallery" so that customers and search for our application and add it themselves.

**Comment by omarestrella** [comment]
In order to get listed in the directory, there is some information we need to provide to Microsoft in our app configuration, as well as en email we need to send out. See here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-app-gallery-listing
